/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber' // 1. Import animation hook
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/clover.glb')
  
  // 2. Create the "Handle" to grab the 3D object
  const cloverRef = useRef()

  // 3. The Animation Loop (Runs 60 times per second)
  useFrame((state, delta) => {
    if (cloverRef.current) {
        // Spin around vertically
        cloverRef.current.rotation.z += delta * 0.5; 
        // Gentle Bobbing up and down (math.sin creates a wave)
        cloverRef.current.rotation.x = -1.57 + Math.sin(state.clock.elapsedTime) * 0.1; 
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh 
        ref={cloverRef} // 4. Attach the handle to the mesh
        geometry={nodes.path1.geometry} 
        position={[-0.409, 0.212, 0.051]} 
        rotation={[-1.57, 0, 0]} 
        scale={-322.44} 
        castShadow 
        receiveShadow
      >
          <meshStandardMaterial 
            color="#009A44"       
            roughness={0.4}       
            metalness={0.1}       
            emissive="#004400"    
            emissiveIntensity={0.2}
            side={THREE.DoubleSide} 
          />
      </mesh>
    </group>
  )
}

useGLTF.preload('/clover.glb')