/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/clover.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.path1.geometry} 
        position={[-0.409, 0.212, 0.051]} 
        rotation={[-1.57, 0, 0]} 
        scale={-322.44} 
        castShadow 
        receiveShadow
      >
          <meshStandardMaterial 
            color="#009A44"       
            roughness={0.4}       
            metalness={0.1}       
            emissive="#004400"    
            emissiveIntensity={0.2}
            side={THREE.DoubleSide} 
          />
      </mesh>
    </group>
  )
}

useGLTF.preload('/clover.glb')